services:
  - type: web
    name: hotelshears
    env: python
    buildCommand: |
      # Installation de Chrome
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: WEB_CONCURRENCY
        value: 2
      - key: GUNICORN_TIMEOUT
        value: 300
      - key: PORT
        value: 10000
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
    plan: free
    autoDeploy: true 