services:
  - type: web
    name: hotelshears
    env: python
    buildCommand: |
      # Installation des dépendances nécessaires
      apt-get update
      apt-get install -y wget gnupg2 apt-utils
      # Installation de Chrome
      wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y ./google-chrome-stable_current_amd64.deb
      # Vérification de l'installation
      google-chrome --version
      # Installation des dépendances Python
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: WEB_CONCURRENCY
        value: 2
      - key: GUNICORN_TIMEOUT
        value: 300
      - key: PORT
        value: 10000
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: PYTHONUNBUFFERED
        value: "true"
    plan: free
    autoDeploy: true 